- name: handlers
  hosts: web_servers
  vars_files: 
  - variables 
  tasks:
  - name: update_cache
    apt: 
      update_cache: true

  - name: Install Nginx
    apt:
      name: "{{package_nginx.name}}"
      state: "{{package_nginx.state}}"
    changed_when: true
    notify: Copy files   

  - name: trigger
    template:
        src: front/index.j2
        dest: /var/www/html/index.html
    changed_when: true
    notify: Restart Nginx 

  handlers:
    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: /var/www/html/
      loop: "{{ file_names }}"
      changed_when: true
      notify: Restart Nginx
    

    - name: Restart Nginx
      sysvinit:
        name: nginx
        state: restarted